import type { Banner, Coupon, Product, StoreSettings } from "@/lib/types";

const now = "2026-07-10T12:00:00.000-03:00";
const blurDataUrl =
  "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0nMTIwMCcgaGVpZ2h0PSc5MDAnIHZpZXdCb3g9JzAgMCAxMjAwIDkwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cmVjdCB3aWR0aD0nMTIwMCcgaGVpZ2h0PSc5MDAnIGZpbGw9JyMwNzA3MDcnLz48Y2lyY2xlIGN4PSc2MDAnIGN5PSczMjAnIHI9JzQwMCcgZmlsbD0nIzFENkRGRicgZmlsbC1vcGFjaXR5PScwLjE4Jy8+PC9zdmc+";

function productImages(slug: string, alt: string) {
  return [
    {
      id: `img-${slug}-main`,
      url: `/brand/products/${slug}-main.svg`,
      alt: `${alt}, vista principal`,
      position: 1,
      isPrimary: true,
      blurDataUrl,
      width: 1200,
      height: 900,
    },
    {
      id: `img-${slug}-angle`,
      url: `/brand/products/${slug}-angle.svg`,
      alt: `${alt}, vista alternativa`,
      position: 2,
      isPrimary: false,
      blurDataUrl,
      width: 1200,
      height: 900,
    },
    {
      id: `img-${slug}-detail`,
      url: `/brand/products/${slug}-detail.svg`,
      alt: `${alt}, detalle visual`,
      position: 3,
      isPrimary: false,
      blurDataUrl,
      width: 1200,
      height: 900,
    },
  ];
}

function mainImage(slug: string) {
  return `/brand/products/${slug}-main.svg`;
}

export const demoProducts: Product[] = [
  {
    id: "prod-console-ps-demo",
    slug: "consola-playstation-demo",
    name: "Consola PlayStation de ejemplo (demo)",
    shortDescription: "Consola demo para validar catálogo, stock y checkout.",
    description:
      "Publicación de demostración para probar la experiencia de compra de consolas. Reemplazar por una publicación real antes de vender.",
    category: "Consolas",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "PS-DEMO",
    priceCents: 89000000,
    promoPriceCents: 82900000,
    internalCostCents: 70000000,
    sku: "DEMO-CON-PS-001",
    stock: 5,
    lowStockThreshold: 2,
    images: productImages(
      "consola-playstation-demo",
      "Consola PlayStation de ejemplo",
    ),
    mainImage: mainImage("consola-playstation-demo"),
    features: ["Demo", "Producto físico", "Stock controlado"],
    warranty: "Garantía demo pendiente de configurar por administración.",
    deliveryTerms: "Envío nacional configurable o retiro si se habilita.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola PlayStation demo | T.PlayGames",
    seoDescription: "Consola PlayStation de ejemplo para entorno demo.",
    variants: [
      {
        id: "var-console-ps-1tb",
        sku: "DEMO-CON-PS-001-1TB",
        label: "Edición demo 1 TB",
        capacity: "1 TB",
        platform: "PlayStation",
        format: "physical",
        condition: "new",
        priceCents: 82900000,
        stock: 3,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-console-xbox-demo",
    slug: "consola-xbox-demo",
    name: "Consola Xbox de ejemplo (demo)",
    shortDescription: "Consola demo para probar stock y checkout físico.",
    description:
      "Publicación de demostración para flujo de compra física. No representa una oferta real.",
    category: "Consolas",
    platform: "Xbox",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "XB-DEMO",
    priceCents: 76000000,
    sku: "DEMO-CON-XB-001",
    stock: 4,
    lowStockThreshold: 2,
    images: productImages("consola-xbox-demo", "Consola Xbox de ejemplo"),
    mainImage: mainImage("consola-xbox-demo"),
    features: ["Demo", "Producto físico", "Envío configurable"],
    warranty: "Garantía demo pendiente de revisión.",
    deliveryTerms: "Envío a domicilio configurable por provincia.",
    publicationStatus: "published",
    featured: true,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola Xbox demo | T.PlayGames",
    seoDescription: "Consola Xbox de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-console-nintendo-demo",
    slug: "consola-nintendo-demo",
    name: "Consola Nintendo de ejemplo (demo)",
    shortDescription: "Consola demo para la categoría Nintendo.",
    description:
      "Producto de demostración para validar catálogo y checkout. No vender sin reemplazar datos.",
    category: "Consolas",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "NT-DEMO",
    priceCents: 64000000,
    sku: "DEMO-CON-NT-001",
    stock: 6,
    lowStockThreshold: 2,
    images: productImages(
      "consola-nintendo-demo",
      "Consola Nintendo de ejemplo",
    ),
    mainImage: mainImage("consola-nintendo-demo"),
    features: ["Demo", "Producto físico", "Nueva"],
    warranty: "Garantía demo pendiente de configuración.",
    deliveryTerms: "Envío a domicilio configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola Nintendo demo | T.PlayGames",
    seoDescription: "Consola Nintendo de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-control-ps-demo",
    slug: "control-playstation-demo",
    name: "Control PlayStation de ejemplo (demo)",
    shortDescription: "Control demo con variantes de color.",
    description: "Producto demo para probar carrito, variantes y stock.",
    category: "Controles",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-PS-DEMO",
    priceCents: 11500000,
    promoPriceCents: 9900000,
    sku: "DEMO-CTRL-PS-001",
    stock: 12,
    lowStockThreshold: 3,
    images: productImages(
      "control-playstation-demo",
      "Control PlayStation de ejemplo",
    ),
    mainImage: mainImage("control-playstation-demo"),
    features: ["Demo", "Color configurable", "Stock por variante"],
    warranty: "Garantía demo pendiente.",
    deliveryTerms: "Envío configurable.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control PlayStation demo | T.PlayGames",
    seoDescription: "Control PlayStation de ejemplo para entorno demo.",
    variants: [
      {
        id: "var-control-ps-blue",
        sku: "DEMO-CTRL-PS-BLU",
        label: "Azul demo",
        color: "Azul",
        priceCents: 9900000,
        stock: 8,
        available: true,
      },
      {
        id: "var-control-ps-white",
        sku: "DEMO-CTRL-PS-WHT",
        label: "Blanco demo",
        color: "Blanco",
        stock: 4,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-control-xbox-demo",
    slug: "control-xbox-demo",
    name: "Control Xbox de ejemplo (demo)",
    shortDescription: "Control físico de demostración.",
    description: "Control demo para validar compras físicas.",
    category: "Controles",
    platform: "Xbox",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-XB-DEMO",
    priceCents: 10200000,
    sku: "DEMO-CTRL-XB-001",
    stock: 10,
    lowStockThreshold: 3,
    images: productImages("control-xbox-demo", "Control Xbox de ejemplo"),
    mainImage: mainImage("control-xbox-demo"),
    features: ["Demo", "Producto físico"],
    warranty: "Garantía demo pendiente.",
    deliveryTerms: "Envío configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control Xbox demo | T.PlayGames",
    seoDescription: "Control Xbox de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-control-nintendo-demo",
    slug: "control-nintendo-demo",
    name: "Control Nintendo de ejemplo (demo)",
    shortDescription: "Control demo para categoría Nintendo.",
    description: "Producto demo para validar catálogo.",
    category: "Controles",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-NT-DEMO",
    priceCents: 9400000,
    sku: "DEMO-CTRL-NT-001",
    stock: 9,
    lowStockThreshold: 3,
    images: productImages(
      "control-nintendo-demo",
      "Control Nintendo de ejemplo",
    ),
    mainImage: mainImage("control-nintendo-demo"),
    features: ["Demo", "Producto físico"],
    warranty: "Garantía demo pendiente.",
    deliveryTerms: "Envío configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control Nintendo demo | T.PlayGames",
    seoDescription: "Control Nintendo de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-game-physical-demo",
    slug: "juego-fisico-demo",
    name: "Juego físico de ejemplo (demo)",
    shortDescription: "Juego físico demo para checkout con envío.",
    description:
      "Juego físico de demostración. El administrador debe reemplazarlo por un producto real.",
    category: "Juegos",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-PHY-DEMO",
    priceCents: 7200000,
    promoPriceCents: 6400000,
    sku: "DEMO-GAME-PHY-001",
    stock: 20,
    lowStockThreshold: 5,
    images: productImages("juego-fisico-demo", "Juego físico de ejemplo"),
    mainImage: mainImage("juego-fisico-demo"),
    features: ["Demo", "Formato físico", "Envío requerido"],
    warranty: "Garantía demo pendiente.",
    deliveryTerms: "Se despacha luego de confirmar pago.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego físico demo | T.PlayGames",
    seoDescription: "Juego físico de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-game-digital-demo",
    slug: "juego-digital-demo",
    name: "Juego digital de ejemplo (demo)",
    shortDescription: "Juego digital demo con entrega manual segura.",
    description:
      "Producto digital demo. La entrega se procesa manualmente desde el panel administrativo luego del pago aprobado.",
    category: "Juegos",
    platform: "PC",
    type: "digital",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-DIG-DEMO",
    priceCents: 3900000,
    sku: "DEMO-GAME-DIG-001",
    stock: 50,
    lowStockThreshold: 10,
    images: productImages("juego-digital-demo", "Juego digital de ejemplo"),
    mainImage: mainImage("juego-digital-demo"),
    features: ["Demo", "Digital", "Entrega manual protegida"],
    warranty: "Condiciones digitales pendientes de revisión legal.",
    deliveryTerms:
      "Entrega manual por canal configurado luego de pago aprobado.",
    publicationStatus: "published",
    featured: true,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego digital demo | T.PlayGames",
    seoDescription: "Juego digital de ejemplo con entrega manual.",
    variants: [
      {
        id: "var-game-digital-pc",
        sku: "DEMO-GAME-DIG-PC",
        label: "PC digital demo",
        platform: "PC",
        format: "digital",
        stock: 50,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-game-presale-demo",
    slug: "juego-preventa-demo",
    name: "Juego en preventa de ejemplo (demo)",
    shortDescription: "Producto demo para preventa manual.",
    description:
      "Publicación demo de preventa. No habilitar ventas reales sin condiciones comerciales claras.",
    category: "Juegos",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-PRE-DEMO",
    priceCents: 5800000,
    sku: "DEMO-GAME-PRE-001",
    stock: 15,
    lowStockThreshold: 4,
    images: productImages(
      "juego-preventa-demo",
      "Juego en preventa de ejemplo",
    ),
    mainImage: mainImage("juego-preventa-demo"),
    features: ["Demo", "Preventa informativa", "Condiciones pendientes"],
    warranty: "Garantía demo pendiente.",
    deliveryTerms: "Entrega sujeta a fecha comercial configurada.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego en preventa demo | T.PlayGames",
    seoDescription: "Juego en preventa de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
];

export const demoCoupons: Coupon[] = [
  {
    id: "coupon-demo10",
    code: "DEMO10",
    type: "percentage",
    value: 10,
    minPurchaseCents: 1000000,
    startsAt: "2026-01-01T00:00:00.000-03:00",
    endsAt: "2027-01-01T00:00:00.000-03:00",
    totalLimit: 1000,
    perCustomerLimit: 1,
    active: true,
    redemptions: 0,
  },
  {
    id: "coupon-juegos5000",
    code: "JUEGOS5000",
    type: "fixed",
    value: 500000,
    minPurchaseCents: 3000000,
    startsAt: "2026-01-01T00:00:00.000-03:00",
    applicableCategories: ["Juegos"],
    active: true,
    redemptions: 0,
  },
];

export const demoBanners: Banner[] = [
  {
    id: "banner-main",
    title: "Jugá más. Pagá menos.",
    body: "Consolas, controles y juegos con checkout seguro, stock validado y soporte por WhatsApp.",
    ctaLabel: "Ver catálogo",
    href: "/catalogo",
    active: true,
  },
];

export const defaultStoreSettings: StoreSettings = {
  pickupEnabled: false,
  pickupLabel: "Retiro en punto acordado",
  freeShippingFromCents: 150000000,
  defaultShippingCents: 650000,
  provinceShippingCents: {
    "Buenos Aires": 650000,
    CABA: 480000,
    Cordoba: 720000,
    "Santa Fe": 720000,
    Mendoza: 850000,
  },
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER,
  digitalDeliveryChannel: "email",
  paymentMethods: {
    mercadoPago: true,
    transfer: false,
  },
  transferDiscountPercent: undefined,
  installments: [],
  socialLinks: {
    instagram: undefined,
    tiktok: undefined,
  },
};
