import type { Banner, Coupon, Product, StoreSettings } from "@/lib/types";

const now = "2026-07-10T12:00:00.000-03:00";

export const demoProducts: Product[] = [
  {
    id: "prod-console-ps-demo",
    slug: "consola-playstation-demo",
    name: "Consola PlayStation de ejemplo (demo)",
    shortDescription: "Producto demo para validar compras de consolas.",
    description:
      "Publicacion de demostracion. Reemplazar por una consola real cargada por administracion antes de vender.",
    category: "Consolas",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "PS-DEMO",
    priceCents: 89000000,
    promoPriceCents: 82900000,
    internalCostCents: 70000000,
    sku: "DEMO-CON-PS-001",
    stock: 5,
    lowStockThreshold: 2,
    images: [
      {
        id: "img-console-ps",
        url: "/demo/consola-playstation-demo.svg",
        alt: "Ilustracion demo de consola PlayStation",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/consola-playstation-demo.svg",
    features: ["Demo", "Producto fisico", "Stock controlado"],
    warranty: "Garantia demo pendiente de configurar por administracion.",
    deliveryTerms: "Envio nacional configurable o retiro si se habilita.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola PlayStation demo | T.PlayGames",
    seoDescription: "Consola PlayStation de ejemplo para entorno demo.",
    variants: [
      {
        id: "var-console-ps-1tb",
        sku: "DEMO-CON-PS-001-1TB",
        label: "Edicion demo 1 TB",
        capacity: "1 TB",
        platform: "PlayStation",
        format: "physical",
        condition: "new",
        priceCents: 82900000,
        stock: 3,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-console-xbox-demo",
    slug: "consola-xbox-demo",
    name: "Consola Xbox de ejemplo (demo)",
    shortDescription: "Producto demo para probar variantes y stock.",
    description:
      "Publicacion de demostracion para flujo de compra fisica. No representa una oferta real.",
    category: "Consolas",
    platform: "Xbox",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "XB-DEMO",
    priceCents: 76000000,
    sku: "DEMO-CON-XB-001",
    stock: 4,
    lowStockThreshold: 2,
    images: [
      {
        id: "img-console-xbox",
        url: "/demo/consola-xbox-demo.svg",
        alt: "Ilustracion demo de consola Xbox",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/consola-xbox-demo.svg",
    features: ["Demo", "Producto fisico", "Envio configurable"],
    warranty: "Garantia demo pendiente de revision.",
    deliveryTerms: "Envio a domicilio configurable por provincia.",
    publicationStatus: "published",
    featured: true,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola Xbox demo | T.PlayGames",
    seoDescription: "Consola Xbox de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-console-nintendo-demo",
    slug: "consola-nintendo-demo",
    name: "Consola Nintendo de ejemplo (demo)",
    shortDescription: "Consola demo para la categoria Nintendo.",
    description:
      "Producto de demostracion para validar catalogo y checkout. No vender sin reemplazar datos.",
    category: "Consolas",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "NT-DEMO",
    priceCents: 64000000,
    sku: "DEMO-CON-NT-001",
    stock: 6,
    lowStockThreshold: 2,
    images: [
      {
        id: "img-console-nintendo",
        url: "/demo/consola-nintendo-demo.svg",
        alt: "Ilustracion demo de consola Nintendo",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/consola-nintendo-demo.svg",
    features: ["Demo", "Producto fisico", "Nueva"],
    warranty: "Garantia demo pendiente de configuracion.",
    deliveryTerms: "Envio a domicilio configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Consola Nintendo demo | T.PlayGames",
    seoDescription: "Consola Nintendo de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-control-ps-demo",
    slug: "control-playstation-demo",
    name: "Control PlayStation de ejemplo (demo)",
    shortDescription: "Control demo con variante de color.",
    description: "Producto demo para probar carrito, variantes y stock.",
    category: "Controles",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-PS-DEMO",
    priceCents: 11500000,
    promoPriceCents: 9900000,
    sku: "DEMO-CTRL-PS-001",
    stock: 12,
    lowStockThreshold: 3,
    images: [
      {
        id: "img-control-ps",
        url: "/demo/control-playstation-demo.svg",
        alt: "Ilustracion demo de control PlayStation",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/control-playstation-demo.svg",
    features: ["Demo", "Color configurable", "Stock por variante"],
    warranty: "Garantia demo pendiente.",
    deliveryTerms: "Envio configurable.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control PlayStation demo | T.PlayGames",
    seoDescription: "Control PlayStation de ejemplo para entorno demo.",
    variants: [
      {
        id: "var-control-ps-blue",
        sku: "DEMO-CTRL-PS-BLU",
        label: "Azul demo",
        color: "Azul",
        priceCents: 9900000,
        stock: 8,
        available: true,
      },
      {
        id: "var-control-ps-white",
        sku: "DEMO-CTRL-PS-WHT",
        label: "Blanco demo",
        color: "Blanco",
        stock: 4,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-control-xbox-demo",
    slug: "control-xbox-demo",
    name: "Control Xbox de ejemplo (demo)",
    shortDescription: "Control fisico de demostracion.",
    description: "Control demo para validar compras fisicas.",
    category: "Controles",
    platform: "Xbox",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-XB-DEMO",
    priceCents: 10200000,
    sku: "DEMO-CTRL-XB-001",
    stock: 10,
    lowStockThreshold: 3,
    images: [
      {
        id: "img-control-xbox",
        url: "/demo/control-xbox-demo.svg",
        alt: "Ilustracion demo de control Xbox",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/control-xbox-demo.svg",
    features: ["Demo", "Producto fisico"],
    warranty: "Garantia demo pendiente.",
    deliveryTerms: "Envio configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control Xbox demo | T.PlayGames",
    seoDescription: "Control Xbox de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-control-nintendo-demo",
    slug: "control-nintendo-demo",
    name: "Control Nintendo de ejemplo (demo)",
    shortDescription: "Control demo para categoria Nintendo.",
    description: "Producto demo para validar catalogo.",
    category: "Controles",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "CTRL-NT-DEMO",
    priceCents: 9400000,
    sku: "DEMO-CTRL-NT-001",
    stock: 9,
    lowStockThreshold: 3,
    images: [
      {
        id: "img-control-nintendo",
        url: "/demo/control-nintendo-demo.svg",
        alt: "Ilustracion demo de control Nintendo",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/control-nintendo-demo.svg",
    features: ["Demo", "Producto fisico"],
    warranty: "Garantia demo pendiente.",
    deliveryTerms: "Envio configurable.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Control Nintendo demo | T.PlayGames",
    seoDescription: "Control Nintendo de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-game-physical-demo",
    slug: "juego-fisico-demo",
    name: "Juego fisico de ejemplo (demo)",
    shortDescription: "Juego fisico demo para checkout con envio.",
    description:
      "Juego fisico de demostracion. El administrador debe reemplazarlo por un producto real.",
    category: "Juegos",
    platform: "PlayStation",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-PHY-DEMO",
    priceCents: 7200000,
    promoPriceCents: 6400000,
    sku: "DEMO-GAME-PHY-001",
    stock: 20,
    lowStockThreshold: 5,
    images: [
      {
        id: "img-game-physical",
        url: "/demo/juego-fisico-demo.svg",
        alt: "Ilustracion demo de juego fisico",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/juego-fisico-demo.svg",
    features: ["Demo", "Formato fisico", "Envio requerido"],
    warranty: "Garantia demo pendiente.",
    deliveryTerms: "Se despacha luego de confirmar pago.",
    publicationStatus: "published",
    featured: true,
    offer: true,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego fisico demo | T.PlayGames",
    seoDescription: "Juego fisico de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
  {
    id: "prod-game-digital-demo",
    slug: "juego-digital-demo",
    name: "Juego digital de ejemplo (demo)",
    shortDescription: "Juego digital demo con entrega manual segura.",
    description:
      "Producto digital demo. La entrega se procesa manualmente desde el panel administrativo luego del pago aprobado.",
    category: "Juegos",
    platform: "PC",
    type: "digital",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-DIG-DEMO",
    priceCents: 3900000,
    sku: "DEMO-GAME-DIG-001",
    stock: 50,
    lowStockThreshold: 10,
    images: [
      {
        id: "img-game-digital",
        url: "/demo/juego-digital-demo.svg",
        alt: "Ilustracion demo de juego digital",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/juego-digital-demo.svg",
    features: ["Demo", "Digital", "Entrega manual protegida"],
    warranty: "Condiciones digitales pendientes de revision legal.",
    deliveryTerms:
      "Entrega manual por canal configurado luego de pago aprobado.",
    publicationStatus: "published",
    featured: true,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego digital demo | T.PlayGames",
    seoDescription: "Juego digital de ejemplo con entrega manual.",
    variants: [
      {
        id: "var-game-digital-pc",
        sku: "DEMO-GAME-DIG-PC",
        label: "PC digital demo",
        platform: "PC",
        format: "digital",
        stock: 50,
        available: true,
      },
    ],
    demo: true,
  },
  {
    id: "prod-game-presale-demo",
    slug: "juego-preventa-demo",
    name: "Juego en preventa de ejemplo (demo)",
    shortDescription: "Producto demo para preventa manual.",
    description:
      "Publicacion demo de preventa. No habilitar ventas reales sin condiciones comerciales claras.",
    category: "Juegos",
    platform: "Nintendo",
    type: "physical",
    condition: "new",
    brand: "Marca demo",
    model: "GAME-PRE-DEMO",
    priceCents: 5800000,
    sku: "DEMO-GAME-PRE-001",
    stock: 15,
    lowStockThreshold: 4,
    images: [
      {
        id: "img-game-presale",
        url: "/demo/juego-preventa-demo.svg",
        alt: "Ilustracion demo de juego en preventa",
        position: 1,
        isPrimary: true,
      },
    ],
    mainImage: "/demo/juego-preventa-demo.svg",
    features: ["Demo", "Preventa informativa", "Condiciones pendientes"],
    warranty: "Garantia demo pendiente.",
    deliveryTerms: "Entrega sujeta a fecha comercial configurada.",
    publicationStatus: "published",
    featured: false,
    offer: false,
    createdAt: now,
    updatedAt: now,
    seoTitle: "Juego en preventa demo | T.PlayGames",
    seoDescription: "Juego en preventa de ejemplo para entorno demo.",
    variants: [],
    demo: true,
  },
];

export const demoCoupons: Coupon[] = [
  {
    id: "coupon-demo10",
    code: "DEMO10",
    type: "percentage",
    value: 10,
    minPurchaseCents: 1000000,
    startsAt: "2026-01-01T00:00:00.000-03:00",
    endsAt: "2027-01-01T00:00:00.000-03:00",
    totalLimit: 1000,
    perCustomerLimit: 1,
    active: true,
    redemptions: 0,
  },
  {
    id: "coupon-juegos5000",
    code: "JUEGOS5000",
    type: "fixed",
    value: 500000,
    minPurchaseCents: 3000000,
    startsAt: "2026-01-01T00:00:00.000-03:00",
    applicableCategories: ["Juegos"],
    active: true,
    redemptions: 0,
  },
];

export const demoBanners: Banner[] = [
  {
    id: "banner-main",
    title: "Jugá más. Pagá menos.",
    body: "Consolas, controles y juegos con checkout seguro, stock validado y soporte por WhatsApp.",
    ctaLabel: "Ver catalogo",
    href: "/catalogo",
    active: true,
  },
];

export const defaultStoreSettings: StoreSettings = {
  pickupEnabled: false,
  pickupLabel: "Retiro en punto acordado",
  freeShippingFromCents: 150000000,
  defaultShippingCents: 650000,
  provinceShippingCents: {
    "Buenos Aires": 650000,
    "CABA": 480000,
    Cordoba: 720000,
    "Santa Fe": 720000,
    Mendoza: 850000,
  },
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER,
  digitalDeliveryChannel: "email",
};
